default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: wedge-project-jbangtson
      dataset: the_wedge_dataset
      threads: 1
      timeout_seconds: 300
